"""
RUSI Trader AI

Trading Runtime State

Single authoritative runtime state for the application.

The Trading Engine publishes the latest successfully
processed cycle here.

Backend services and the Flutter application read
this state instead of independently requesting broker
market data.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class TradingRuntimeState:

    """
    Latest successfully processed trading cycle.

    Every field represents the latest runtime information
    generated by the trading engine.
    """

    # ---------------------------------------------------------
    # Runtime
    # ---------------------------------------------------------

    cycle_id: int = 0

    updated_time: str = ""

    data_status: str = "UNKNOWN"

    # ---------------------------------------------------------
    # Market
    # ---------------------------------------------------------

    snapshot: Any = None

    instrument: Any = None

    live_price: float | None = None

    # Live LTP of the currently selected option contract.
    #
    # This is intentionally separate from live_price because
    # live_price represents the primary runtime instrument.
    option_live_price: float | None = None

    # ---------------------------------------------------------
    # Intelligence
    # ---------------------------------------------------------

    feature_store: Any = None

    evidence: Any = None

    intelligence: Any = None

    decision: Any = None

    recommendation: Any = None

    # ---------------------------------------------------------
    # AI Suggestions
    # ---------------------------------------------------------

    suggestions: list[Any] = field(
        default_factory=list
    )

    # ---------------------------------------------------------
    # Execution
    # ---------------------------------------------------------

    execution_policy: Any = None

    order: Any = None

    risk_result: Any = None

    broker_result: Any = None

    # ---------------------------------------------------------
    # Position
    # ---------------------------------------------------------

    # Latest/current position.
    position: Any = None

    # Complete runtime position registry.
    # Contains both OPEN and CLOSED positions.
    positions: list[Any] = field(
        default_factory=list
    )

    # ---------------------------------------------------------
    # Portfolio
    # ---------------------------------------------------------

    portfolio: Any = None

    portfolio_summary: Any = None
