"""
RUSI Trader AI

Trading Runtime State

Single authoritative runtime state for the application.

The Trading Engine publishes the latest successfully
processed cycle here.

Backend services and the Flutter application read
this state instead of independently requesting broker
market data.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class TradingRuntimeState:

    """
    Latest successfully processed trading cycle.

    Every field represents the latest runtime information
    generated by the trading engine.
    """

    # ---------------------------------------------------------
    # Runtime
    # ---------------------------------------------------------

    cycle_id: int = 0

    updated_time: str = ""

    data_status: str = "UNKNOWN"

    # ---------------------------------------------------------
    # Market
    # ---------------------------------------------------------

    snapshot: Any = None

    instrument: Any = None

    live_price: float | None = None

    # ---------------------------------------------------------
    # Intelligence
    # ---------------------------------------------------------

    feature_store: Any = None

    evidence: Any = None

    intelligence: Any = None

    decision: Any = None

    recommendation: Any = None

    # ---------------------------------------------------------
    # AI Suggestions
    # ---------------------------------------------------------

    suggestions: list[Any] = field(
        default_factory=list
    )

    # ---------------------------------------------------------
    # Execution
    # ---------------------------------------------------------

    execution_policy: Any = None

    order: Any = None

    risk_result: Any = None

    broker_result: Any = None

    # ---------------------------------------------------------
    # Position
    # ---------------------------------------------------------

    position: Any = None

    # ---------------------------------------------------------
    # Portfolio
    # ---------------------------------------------------------

    portfolio: Any = None

    portfolio_summary: Any = None
