"""
============================================================
RUSI Trader AI

Trading Runtime Manager

Singleton runtime manager.

Responsible for publishing the latest completed trading
cycle to the application's runtime state.
============================================================
"""

from __future__ import annotations

from threading import Lock
from typing import Any

from trading.runtime.runtime_state import (
    TradingRuntimeState,
)


class RuntimeManager:

    _instance = None

    _lock = Lock()

    # ---------------------------------------------------------
    # Singleton
    # ---------------------------------------------------------

    def __new__(cls):

        with cls._lock:

            if cls._instance is None:

                cls._instance = super().__new__(cls)

                cls._instance.state = (
                    TradingRuntimeState()
                )

                cls._instance._cycle_id = 0

        return cls._instance

    # ---------------------------------------------------------
    # Get Runtime State
    # ---------------------------------------------------------

    def get_state(self) -> TradingRuntimeState:

        return self.state

    # ---------------------------------------------------------
    # Publish Runtime State
    # ---------------------------------------------------------

    def update(
        self,
        **kwargs: Any,
    ) -> None:
        """
        Publish one completed trading cycle.

        The incoming runtime values are validated first.
        A new TradingRuntimeState is then created and
        published as one complete state.
        """

        # -----------------------------------------------------
        # Supported fields
        # -----------------------------------------------------

        valid_fields = set(
            TradingRuntimeState.__dataclass_fields__.keys()
        )

        # -----------------------------------------------------
        # Validate incoming fields
        # -----------------------------------------------------

        unknown_fields = (
            set(kwargs.keys()) - valid_fields
        )

        if unknown_fields:

            raise ValueError(
                "Unknown runtime state fields: "
                + ", ".join(
                    sorted(unknown_fields)
                )
            )

        # -----------------------------------------------------
        # Next cycle
        # -----------------------------------------------------

        next_cycle_id = (
            self._cycle_id + 1
        )

        # -----------------------------------------------------
        # Start from previous state
        #
        # This preserves fields that are not supplied in the
        # current update.
        # -----------------------------------------------------

        state_values = {}

        for field_name in valid_fields:

            state_values[field_name] = getattr(
                self.state,
                field_name,
            )

        # -----------------------------------------------------
        # Apply new runtime values
        # -----------------------------------------------------

        for key, value in kwargs.items():

            state_values[key] = value

        # -----------------------------------------------------
        # Runtime cycle ID
        # -----------------------------------------------------

        state_values["cycle_id"] = (
            next_cycle_id
        )

        # -----------------------------------------------------
        # Data status
        #
        # Until the live market-data engine is implemented,
        # a snapshot generated by the current execution
        # pipeline is explicitly marked HISTORICAL.
        # -----------------------------------------------------

        if "data_status" not in kwargs:

            if kwargs.get("snapshot") is not None:

                state_values["data_status"] = (
                    "HISTORICAL"
                )

        # -----------------------------------------------------
        # Create complete next state
        # -----------------------------------------------------

        next_state = TradingRuntimeState(
            **state_values
        )

        # -----------------------------------------------------
        # Publish complete state
        # -----------------------------------------------------

        self.state = next_state

        self._cycle_id = (
            next_cycle_id
        )
