########################################################################
#
# RUSI Trader AI
#
# Market Sessions
#
########################################################################

markets:

  NSE:

    enabled: true

    timezone: Asia/Kolkata

    sessions:

      - open: "09:15"
        close: "15:30"

  NFO:

    enabled: true

    timezone: Asia/Kolkata

    sessions:

      - open: "09:15"
        close: "15:30"

    new_entry_cutoff: "15:29"

  BSE:

    enabled: true

    timezone: Asia/Kolkata

    sessions:

      - open: "09:15"
        close: "15:30"

  MCX:

    enabled: true

    timezone: Asia/Kolkata

    sessions:

      - open: "09:00"
        close: "23:30"
